### PR TITLE
Trace: Inc and Exc Time Functions

### PR DESCRIPTION
**Pull request by adityaranjan**
- matches enter and leave rows
- call stack depth column
- parent and child relationships between functions
- inc and exc times

### CODE REVIEW

**Comment by jordanmarry** [comment]
If we wanted to use this for nsight/hpctoolkit readers, wouldn't there be issues since those two files don't provide a Location ID column?

**Comment by adityaranjan** [comment]
> If we wanted to use this for nsight/hpctoolkit readers, wouldn't there be issues since those two files don't provide a Location ID column?

You are right. In general, there is currently a discrepancy between all readers with respect to the column names and certain values in the DataFrame.

As of right now, the location id, location id type, location group id, and location group type columns are just to mirror the data OTF2 provides. OTF2 traces can be heterogenous (CPU/GPU), so Location ID Type can be "ACCELERATOR_STREAM", "CPU_THREAD", "METRIC", "UNKNOWN", etc. Similarly, Location Group ID Type can be "ACCELERATOR", "PROCESS", etc.

This brings up two things we should all do/discuss:
1. Formalizing the Schema for the DataFrame - common columns shared by all readers, exact names for columns, names for event types (Enter/Leave vs Entry/Exit), etc.
2. How to handle columns when the trace is heterogeneous, multithreaded (which the other readers support too), etc. One option is to always keep information like the stuff I mentioned above. However, this might be redundant. For example, it might be better to have only a Rank/Process column if the trace is single threaded but multi-process. If the trace has only one thread and process, maybe it is better to have neither. Similarly, it is probably only worth storing the location type (CPU/GPU) if the trace is heterogeneous. I think it depends on how we want to store the data.

**Review by jordanmarry — APPROVED** [review]

**Comment by hsirkar** [comment]
To do: add "matching times" column for timeline view

**Comment by adityaranjan** [comment]
> To do: add "matching times" column for timeline view

resolved

note:
still need to figure out what columns to add, will depend on extent of information provided to user
as well as how much we want to expose in the trace timeline viz

**Comment by hsirkar** [comment]
You left the changes for the otf2 and hpctoolkit readers in this branch -- is this intentional?

**Comment by adityaranjan** [comment]
> You left the changes for the otf2 and hpctoolkit readers in this branch -- is this intentional?

Leaving the parallelization one was not, I'll get rid of that, but we should only be able to use this function once we standardize the readers, so yes, that was. Once we merge the pr, I'll rebase this one and those changes should not be relevant.

**Pull request closed without merging**
